common_configs:
  source_bucket: s3://source_bkt
  destination_bucket: s3://tfs-lemontree-de

rob:
  job_type: spark
  partitions: 1
  output_path: /playground/pnl/rob/test

pace:
  job_type: python
  notify_list: mgr2_tfs@lemontreehotels.com,de1_tfs@lemontreehotels.com,ade1_tfs@lemontreehotels.com,sde1_tfs@lemontreehotels.com,pde_tfs@lemontreehotels.com


local:
  job_type: python
  db: reporting_local
  table: users_local
  filter_column: status_local
  spark_configs:
    spark.executor.memory: "1g"
    spark.driver.memory: "1g"
    spark.sql.shuffle.partitions: "50"
    spark.default.parallelism: "10"

robDaily:
  partitions: 1
  output_path: /input_files/rob/rob_daily

robBulk:
  partitions: 1
  output_path: /input_files/rob/rob_bulk

matRobDaily:
  partitions: 1
  output_path: /input_files/rob/mat_rob_daily

matRobBulk:
  partitions: 1
  output_path: /input_files/rob/mat_rob_bulk